### ISSUE TITLE
Add raytrace block from patcher2 and cleaner view

### ISSUE THREAD

**Issue by PyICoder** [asbyth/Patcher#6]
The same idea as https://www.curseforge.com/minecraft/mc-mods/cleanview as to get rid of particles in view and love the raytrace block from patcher2.

**Comment by asbyth** [comment]
why not just use CleanView since it's a 1.8 mod anyway? and I've been looking into how to get the Raytrace Blocks feature in, but no real way of knowing how, I can look more into it later
