### ISSUE TITLE
Patcher 1.1 crashing game, Patcher 1.0 working fine.

### ISSUE THREAD

**Issue by K1569GHENT** [asbyth/Patcher#7]
Exactly what the title says, forge 1.8.9 - 11.15.1.1722 (recommended)
Game crashes immediately after launch (after the launcher closes and tries to open the actual game)
"game crash" "an unexpected issue and so on"
Patcher 1.0 was working fine, when i open the code for patcher 1.1 in eclipse it's crammed with errors.

**Comment by asbyth** [comment]
well you're at the wrong place as this is a very old version of patcher, join our discord for support discord.gg/sk1er
